# Generated by Django 3.2.9 on 2021-11-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appG7C4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.IntegerField(default=0),
        ),
    ]
