# Generated by Django 3.2.7 on 2021-11-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appG7C4', '0004_auto_20211119_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/users/'),
        ),
    ]
