# Generated by Django 3.2.7 on 2021-11-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appG7C4', '0006_productcategory_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appG7C4.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appG7C4.user'),
            preserve_default=False,
        ),
    ]
