# Generated by Django 3.2.7 on 2021-12-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appG7C4', '0007_auto_20211125_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/category/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/publications/'),
        ),
    ]
